const projects = [
        {
        id: 0,
        recentProjects: false,
        projectsPage: false,
        uiuxPage: false,
        fullStackPage: true,
        marketingPage: false,
        url: "https://github.com/susanzh4ng",
        urlid: "github",
        coverImg: require("./images/github_cover.png"),
        title: "Susan's Github",
        subtitle: "",
        description: "... that she casually contributes to",
        category: "technology",
    },
    {
        id: 2,
        recentProjects: true,
        projectsPage: true,
        uiuxPage: true,
        fullStackPage: false,
        marketingPage: false,
        url: "orgportal",
        urlid: "orgportal",
        coverImg: require("./pages/OrgPortal/OrgPortalImages/orgportal_cover.png"),
        title: "OrgPortal",
        subtitle: "",
        description: "UT Dallas’s student organization portal, built with love by a UT Dallas student organization",
        category: "UI/UX",
    },
    {
        id: 3,
        recentProjects: true,
        projectsPage: true,
        uiuxPage: true,
        fullStackPage: false,
        marketingPage: true,
        url: "utdesign-capstone",
        urlid: "utdesign",
        coverImg: require("./pages/UTDesignCapstone/UTDesignCapstoneImages/utdesigncapstone_cover.png"),
        title: "UTDesign® Capstone",
        subtitle: "for UT Dallas",
        description: "Redesigning UTDesign® Capstone's websites",
        category: "UI/UX, Marketing",
    },
    {
        id: 7,
        recentProjects: false,
        projectsPage: true,
        uiuxPage: false,
        fullStackPage: false,
        marketingPage: true,
        url: "zhoushan2024",
        urlid: "zhoushan",
        coverImg: require("./pages/Zhoushan/ZhoushanImages/zhoushan2024_cover.png"),
        title: "Zhoushan 2024",
        subtitle: "",
        description: "Look of the Games for the fictitious Zhoushan 2024 Summer Olympics",
        category: "Marketing",
    },
    {
        id: 8,
        recentProjects: false,
        projectsPage: true,
        uiuxPage: true,
        fullStackPage: false,
        marketingPage: false,
        url: "grow-with-google",
        urlid: "grow",
        coverImg: require("./pages/Grow/GrowImages/growwithgoogle_cover.png"),
        title: "Grow",
        subtitle: "with Google",
        description: "Career discovery at your fingertips through a fictitious Google product",
        category: "UI/UX",
    },
    {
        id: 9,
        recentProjects: false,
        projectsPage: true,
        uiuxPage: true,
        fullStackPage: false,
        marketingPage: true,
        url: "utd-capstone-programs",
        urlid: "capstones",
        coverImg: require("./pages/UTDCapstone/UTDCapstoneImages/utdseniorcapstoneprograms_cover.png"),
        title: "UTD Capstone Programs",
        subtitle: "for UT Dallas",
        description: "UT Dallas's senior capstone programs' landing page",
        category: "UIUX, Marketing",
    },
    /*{
        id: 5,
        recentProjects: true,
        projectsPage: true,
        uiuxPage: true,
        fullStackPage: false,
        marketingPage: false,
        url: "planne",
        urlid: "planne",
        coverImg: require("./pages/Planne/PlanneImages/planne_cover.png"),
        title: "Planne",
        subtitle: "",
        description: "Plan the steps towards success, one day at a time!",
        category: "UI/UX",
    },*/
    {
        id: 10,
        recentProjects: false,
        projectsPage: true,
        uiuxPage: false,
        fullStackPage: false,
        marketingPage: true,
        url: "wehack2024",
        urlid: "wehack",
        coverImg: require("./pages/Wehack/WehackImages/wehack_cover.png"),
        title: "WEHack 2024",
        subtitle: "at UT Dallas",
        description: "Branding design for Dallas's largest gender-inclusive hackathon",
        category: "Marketing",
    },
    {
        id: 11,
        recentProjects: false,
        projectsPage: true,
        uiuxPage: false,
        fullStackPage: false,
        marketingPage: true,
        url: "comet-gala2024",
        urlid: "gala",
        coverImg: require("./pages/CometGala/CometGalaImages/cometgala_cover.png"),
        title: "Comet Gala 2024",
        subtitle: "for AIGA UTD",
        description: "Branding design for AIGA UT Dallas's gala",
        category: "Marketing",
    },
    /*{
        id: 8,
        recentProjects: false,
        projectsPage: true,
        uiuxPage: false,
        fullStackPage: true,
        marketingPage: false,
        url: "legalease",
        urlid: "legalease",
        coverImg: require("./pages/Legalease/LegaleaseImages/legalease_cover.png"),
        title: "Legalease",
        subtitle: "",
        description: "Chrome extension that webscrapes legal definitions",
        category: "Full-stack",
    },
    {
        id: 9,
        recentProjects: false,
        projectsPage: true,
        uiuxPage: false,
        fullStackPage: true,
        marketingPage: false,
        url: "writeright",
        urlid: "writeright",
        coverImg: require("./pages/WriteRight/WriteRightImages/writeright_cover.png"),
        title: "WriteRight",
        subtitle: "for UTD's ACM Projects",
        description: "The one-stop shop for creative writers at any stage of the writing process!",
        category: "Full-stack",
    }*/
]

export default projects