const projects = [
    {
        id: 1,
        recentProjects: true,
        projectsPage: true,
        uiuxPage: true,
        fullStackPage: false,
        marketingPage: true,
        url: "utdesign-capstone",
        coverImg: require("./pages/UTDesignCapstone/UTDesignCapstoneImages/UTDesignCapstone-Banner.png"),
        title: "UTDesign® Capstone",
        subtitle: "for UT Dallas",
        description: "Redesigning UTDesign® Capstone's websites",
        category: "UI/UX, Marketing",
    },
    {
        id: 2,
        recentProjects: true,
        projectsPage: true,
        uiuxPage: true,
        fullStackPage: false,
        marketingPage: true,
        url: "utd-capstone-programs",
        coverImg: require("./pages/UTDCapstone/UTDCapstoneImages/UTD-Banner.png"),
        title: "UTD Capstone Programs",
        subtitle: "for UT Dallas",
        description: "UT Dallas's senior capstone programs' landing page",
        category: "UIUX, Marketing",
    },
    {
        id: 3,
        recentProjects: true,
        projectsPage: true,
        uiuxPage: true,
        fullStackPage: false,
        marketingPage: false,
        url: "pixy",
        coverImg: require("./pages/Pixy/PixyImages/Pixy-Banner.png"),
        title: "Pixy",
        subtitle: "",
        description: "A reference image lookup app — made for and designed by artists. ",
        category: "UI/UX",
    },
    {
        id: 4,
        recentProjects: true,
        projectsPage: true,
        uiuxPage: true,
        fullStackPage: false,
        marketingPage: false,
        url: "planne",
        coverImg: require("./pages/Planne/PlanneImages/Planne-Banner.png"),
        title: "Planne",
        subtitle: "",
        description: "Plan the steps towards success, one day at a time!",
        category: "UI/UX",
    },
    {
        id: 5,
        recentProjects: false,
        projectsPage: true,
        uiuxPage: false,
        fullStackPage: false,
        marketingPage: true,
        url: "comet-gala2024",
        coverImg: require("./pages/CometGala/CometGalaImages/cometGala-banner.png"),
        title: "Comet Gala 2024",
        subtitle: "for AIGA UTD",
        description: "Branding design for AIGA UT Dallas's gala",
        category: "Marketing",
    },
    {
        id: 6,
        recentProjects: false,
        projectsPage: true,
        uiuxPage: false,
        fullStackPage: false,
        marketingPage: true,
        url: "wehack2024",
        coverImg: require("./pages/Wehack/WehackImages/wehack-banner.png"),
        title: "WEHack 2024",
        subtitle: "at UT Dallas",
        description: "Branding design for Dallas's largest gender-inclusive hackathon",
        category: "Marketing",
    },
    {
        id: 7,
        recentProjects: false,
        projectsPage: true,
        uiuxPage: false,
        fullStackPage: true,
        marketingPage: false,
        url: "legalease",
        coverImg: require("./pages/Legalease/LegaleaseImages/Legalease-Banner.png"),
        title: "Legalease",
        subtitle: "",
        description: "Chrome extension that webscrapes legal definitions",
        category: "Full-stack",
    },
    {
        id: 8,
        recentProjects: false,
        projectsPage: true,
        uiuxPage: false,
        fullStackPage: true,
        marketingPage: false,
        url: "writeright",
        coverImg: require("./pages/WriteRight/WriteRightImages/WriteRight-Banner.png"),
        title: "WriteRight",
        subtitle: "for UTD's ACM Projects",
        description: "The one-stop shop for creative writers at any stage of the writing process!",
        category: "Full-stack",
    }
]

export default projects